Global:
    github_token: # https://github.com/settings/tokens

Launcher:
    filename: NorthstarLauncher.exe
    argumnets: -multiple -novid -windowed -noborder -width 3840 -height 2160 +exec
        custom.cfg +cl_showfps 2

Manager:
    repository: FromWau/NorthstarManager
    last_update: '2022-07-25T14:58:37'
    file: NorthstarManager.exe

Mods:
    Northstar:
        repository: R2Northstar/Northstar
        last_update: '2023-06-29T21:47:09'
        install_dir: .
        file: NorthstarLauncher.exe
        exclude_files:
        - ns_startup_args.txt
        - ns_startup_args_dedi.txt

    # Settings / Utility / Frameworks
    ModSettings:
        repository: EladNLG/ModSettings
        last_update: '2023-04-16T18:30:39'
    ReticlesFramework:
        repository: Creamy_jpg/Customisable_Reticles_Framework
        last_update: '2023-04-23T00:18:15'
    ClientKillCallback:
        repository: S2Mods/ClientKillCallback
        last_update: '2023-04-23T11:03:13'
    RemoveMP:
        repository: iTz_Nao/iTz_Nao__Remove_Locked_Multiplayer
        last_update: '2022-05-14T01:08:16'
    EnhancedMenuMod:
        repository: taskinoz/EnhancedMenuMod
        last_update: '2022-02-11T12:32:36'
    #TitanFramework:
    #    repository: The_Peepeepoopoo_man/Titanframework
    #    last_update: '2023-04-10T15:04:58'

    # Skins
    Warpaints:
        repository: Creamy_jpg/WARPAINTS_MINUS
        last_update: '2023-02-22T17:00:40'
    MoreSkins:
        repository: Creamy_jpg/MoreSkinsMinus
        last_update: '2023-02-22T16:09:43'

    # Animations
    Middlenade:
        repository: DINOTICK/Middlenade
        last_update: '2022-10-23T17:08:12'
    SpinnyP2016:
        repository: DINOTICK/SpinnyP2016
        last_update: '2022-10-16T13:00:10'
    Kunai:
        repository: TH3_S4LM0N/kunai_melee
        last_update: '2022-04-05T14:53:52'

    # Models:
    ApexWingman:
        repository: Trinity_Dusk/Dusk_ApexWingman
        last_update: '2022-09-13T06:29:57'
    ApexWingmanElite:
        repository: CNS144/Precision_Caliber_apex_wingmanB3
        last_update: '2023-02-04T20:33:45'
    SpTicks:
        repository: FromWau/SpTicks
        last_update: '2022-03-18T02:03:35'
    #TF1Pilot:
    #    repository: TF1_Mcor_Pilot
    #    last_update: '2022-03-18T02:03:35'
    UwU_EVA8:
        repository: smooshie/EVA8_UwU
        last_update: '2023-05-28T03:52:29'
    RoninBloodySword:
        repository: sammydoodlew/RoninBroadsword_Bloody
        last_update: '2022-10-27T00:51:20'
    NessieNades:
        repository: DINOTICK/NessieNades
        last_update: '2022-04-11T19:30:17'

    # Audio
    EnemySpotted:
        repository: Khalmee/Enemy_Spotted_Grunts
        last_update: '2023-01-08T22:28:11'
    HotHotHot:
        repository: FromWau/HotHotHot
        last_update: '2023-07-01T02:22:37'

    # Fx
    RGBPulse:
        repository: TH3_S4LM0N/RGBPulse
        last_update: '2022-05-24T00:24:47'

    # HUD
    HaloAnnouncer:
        repository: Capt_Diqhedd/HaloAnnouncer
        last_update: '2023-06-04T04:11:37'
    Speedometer:
        repository: S2Mods/SpeedometerV2
        last_update: '2023-01-24T16:03:12'
    FixWeaponDesc:
        repository: NachosChipeados/Fixed_Unused_Weapons_Description
        last_update: '2023-03-23T01:35:07'
    DamageFlyout:
        repository: odds/DamageFlyout
        last_update: '2023-02-22T10:24:37'
    RemoveMuzzle:
        repository: adventure/Remove_Muzzle_Flash
        last_update: '2023-04-28T15:23:34'
    RemoveSunFlares:
        repository: adventure/RemoveSunFlares
        last_update: '2023-04-28T15:23:45'
    CustomScopeFOV:
        repository: Avalar/CustomScopeFOV
        last_update: '2022-08-13T02:26:39'
        exclude_files:
        - mod\scripts\weapons\mp_pistols_fov.txt
    #HUDRevmap:
    #    repository: EladNLG/HUDRevamp
    #    last_update: '2023-01-26T15:57:31'

    # Titans
    RGBIon:
        repository: pYt/RGBIon
        last_update: '2023-01-09T11:36:07'
    OS_Restoration:
        repository: Northstar_Archive/OS_Restoration
        last_update: '2022-11-23T04:31:54'

    # Maps
    WargamesOverhaul:
        repository: S2Mods/WargamesOverhaul
        last_update: '2023-04-10T17:50:55'
    GlitchOverhaul:
        repository: S2Mods/GlitchOverhaul
        last_update: '2023-02-25T12:37:24'
    MapLighting:
        repository: S2Mods/MapLighting
        last_update: '2023-06-23T11:17:19'
    RainAndLightning:
        repository: S2Mods/RainAndLightning
        last_update: '2022-12-22T19:28:07'
    NightCity:
        repository: Rwyn/Night_City
        last_update: '2023-06-20T15:34:48'
    Frostbite:
        repository: Fifty/Frostbite
        last_update: '2022-11-19T18:24:22'

    # Game Modes
    Parkour:
        repository: Alystrasz/Parkour
        last_update: '2023-06-30T21:36:58'
    #Thunderdome:
    #    repository: Thunderdome/Thunderdome
    #    last_update: '2023-03-05T17:01:24'
    BombingRun:
        repository: Alystrasz/BombingRun
        last_update: '2022-08-04T16:33:20'

    # Singleplayer
    RogueLikeBETA:
        repository: EladNLG/RoguelikeBETA
        last_update: '2023-01-28T17:51:48'

    # Menus
    MainMenuBackground:
        repository: FromWau/CustomMainMenuBackground
        last_update: '2023-07-01T15:54:30'
